### ISSUE TITLE
I would like to join your team and contribute with my many years of experience and skills.

### ISSUE THREAD

**Issue by johnsmith0212** [42ByteLabs/geekorm#111]
### What new feature are you looking for / expect?

Hi, I'm Ethan Tan, a seasoned web full-stack and blockchain developer with over 8 years of experience in the industry. I specialize in building robust, scalable web applications and innovative blockchain solutions. Leveraging my expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, I deliver high-quality, secure, and efficient solutions tailored to meet your specific needs.

### Expectations

Nice to have

**Comment by GeekMasher** [comment]
Hi @johnsmith0212 this project is currently under construction and is still being actively developer. If you want to contribute, maybe the best thing to do is use the library and provide feedback.

**Comment by johnsmith0212** [comment]
Don't you hire developers on your team?

**Comment by GeekMasher** [comment]
We aren't currently hiring any developers at 42ByteLabs right now

**Comment by johnsmith0212** [comment]
okay
If you need my help, plz contact me
