### ISSUE TITLE
[Bug]: log crate is used in derive macro

### ISSUE THREAD

**Issue by camilomcatasus** [42ByteLabs/geekorm#58]
### What happened?

Basically I have to add the log crate as a dependency because it seems like in the derive macro (specifically [geekorm-derive/src/parsers/tablebuilder.rs](https://github.com/42ByteLabs/geekorm/blob/363655443d4be2824ff983ea604d2095a4c8d340/geekorm-derive/src/parsers/tablebuilder.rs#L235)) the crate is used. I think this is an oversight, let me know if I'm wrong!

### Version

v0.1

**Comment by GeekMasher** [comment]
@camilomcatasus I think you are right. I added this but it shouldn't be in here. Let me remove it from the derive crate

**Comment by GeekMasher** [comment]
This should be fixed if you update to v0.2.7 now, thanks for the feedback. Keep it coming!

https://github.com/42ByteLabs/geekorm/releases/tag/v0.2.7
